baseURL = "http://blog.chenhq.ren/"
disablePathToLower = true
googleAnalytics = "UA-132232639-1"
hasCJKLanguage = true
languageCode = "en-us"
preserveTaxonomyNames = true
summaryLength = 140
theme = "maupassant"
title = "CodeTalk"
[author]
name = "oddcc"
[params]
author = "oddcc" 
keywords = "golang,go语言,oddcc,java,博客" 
localSearch = true # 启用本地搜索
subtitle = "记录，思考，分享" 
toc = true # 是否开启目录
[params.cc]
link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
[params.sequenceDiagrams]
enable = true 
options = "" # default: "{theme: 'simple'}"
[params.flowchartDiagrams]
enable = true
options = ""
[params.utteranc]
enable = true 
issueTerm = "title" #表示你选择以那种方式让github issue的评论和你的文章关联。
repo = "oddcc/oddcc.github.io" # 存储评论的Repo，格式为 owner/repo
theme = "github-light" # 样式主题，有github-light和github-dark两种
[markup]
[markup.highlight]
lineNos = true
style = "github"
[menu]
[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 3
