baseURL = "http://blog.chenhq.ren/"
languageCode = "en-us"
theme = "maupassant"
title = "CodeTalk"

disablePathToLower = true
hasCJKLanguage = true
preserveTaxonomyNames = true
summaryLength = 140
[author]
name = "oddcc"
[params]
author = "oddcc"
keywords = "golang,go语言,oddcc,java,博客"
subtitle = "记录，思考，分享"
#   busuanzi = true #启用不算子网页统计
#   googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
localSearch = true # 启用本地搜索

# 这里我存放在了主题的static文件夹里，根目录的似乎也可以
#   customCSS = ['douban.css', 'other.css']
# if ['custom.css'], load '/static/css/custom.css' file
#   customJS = ['douban.js']
# if ['custom.js'], load '/static/js/custom.js' file

# 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
toc = true # 是否开启目录
[params.cc]
link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
[params.sequenceDiagrams]
enable = true 
options = "" # default: "{theme: 'simple'}"
[params.flowchartDiagrams]
enable = true
options = ""

[markup]
[markup.highlight]
lineNos = true
style = "github"

[menu]

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 3
